[tool.poetry]
name = "s2sprosody"
version = "0.1.0"
description = ""
authors = ["T0RA <torapira@icloud.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9.0,<4"
pandas = ">=1.0.0"
transformers = "4.43.4"
tensorboardX = "2.6.2.2"
einops = "0.8.0"
torchvision = "0.14.1"
torchaudio = "0.13.1"
cuda-python = "11.8.0"
g2p-en = "2.1.0"
inflect = "4.1.0"
librosa = ">0.7.2"
matplotlib = ">=3.2.2"
numba = "^0.60.0"
numpy = "~1.22.4"
pypinyin = ">= 0.39.0"
pyworld = "^0.3.4"
PyYAML = "6.0"
scikit-learn = "0.24.0"
scipy = "^1.7.2"
soundfile = "0.10.3.post1"
tensorboard = "2.2.2"
tgt = "1.4.4"
torch = "1.13.1"
tqdm = ">=4.46.1"
Unidecode = "1.1.1"
ffmpeg-python = "^0.2.0"
wandb = "^0.18.1"
fastdtw = "^0.3.4"
ffmpeg = "^1.4"
evaluate = "^0.4.3"
jiwer = "^3.1.0"
textgrid = "^1.6.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.931"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"
jupyterlab = "^3.3.0"
bandit = "^1.7.4"
poethepoet = "^0.13.1"
flake8-bugbear = "22.1.11"
flake8-builtins = "1.5.3"
flake8-eradicate = "1.2.0"
pep8-naming = "0.12.1"
flake8-expression-complexity = "0.0.10"
flake8-cognitive-complexity = "0.1.0"
flake8-pytest-style = "1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
