path:
  output_path: "../output/Sign2Speech"
  result_path: "../result/Sign2Speech"

fine-tuning: "./config/VCTK"

optimizer:
  batch_size: 20 # 16
  lr_G_s2a: 0.0001
  lr_D_a: 0.0004
  lr_fine-tuning: 0.001
  betas: [0.5, 0.9]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  discriminator_epoch: 15

loss:
  prosody:
    dist: True
    bins: 16
    dist_loss_type: CELoss
  weight:
    prosody: 0.2
    regdist_mean: 0.3
  PGR:
    margin: 0.0

dataset:
  serial_batches: False

GAN:
  gan_mode: lsgan
  pool_size: 50
  lr_policy: cosine
  lr_decay_iters: 50

step:
  total_step: 50 # 900000
  step_count: 0
  log_step: 50
  synth_step: 1000
  val_step: 1000
  save_epochs: 1
